name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            echo "requirements.txt not found, skipping dependency installation."
          fi

      - name: Initialize Database
        run: |
          if [ -f scripts/init_db.py ]; then
            python scripts/init_db.py
          else
            echo "scripts/init_db.py not found, skipping database initialization."
          fi

      - name: Run tests
        run: |
          if [ -d tests ]; then
            python -m pytest
          else
            echo "No tests found, skipping test execution."
          fi
